### ISSUE TITLE
Recharge la page genere une nouvelle commande

### ISSUE THREAD

**Issue by ppmt** [davidlhoumaud/plxMyShop#15]
Suite a la remarque de @jackplux je pense qu'il serait bien de faire en sorte que lors d'un reload une nouvelle commande ne soit pas générée.

voir le lien pour plus de details

http://forum.pluxml.org/viewtopic.php?pid=50195#p50195

**Comment by mathieu269** [comment]
En voulant rafraichir la page, le navigateur demande une confirmation et si le client persiste, un nouvel e-mail est envoyé mais avec un panier vide.
Donc ce n'est pas vraiment un bug mais juste une amélioration de l'affichage pendant le processus de commande.

**Comment by ppmt** [comment]
Disont une inconvenience.  Il faudrait faire en sorte que meme avec un reload le code ne renvoie pas le mail.

Apparement il faut regarder du cote POST/REDIRECT/GET . J'ai essaye de jouer un peu avec le code mais rien de bien concluant

**Comment by mathieu269** [comment]
bonne idée, je cherchais comment éviter le rafraichissement sans avoir besoin de refaire toutes les pages de commande et Paypal. Mais il suffisait de ne pas envoyer d'e-mail si le panier est vide.
j'ai corrigé dans mes fichiers de développement, ça sera inclus dans le prochain "commit".

**Comment by jackplux** [comment]
Hello Mathieu, :)

Tu peux me dire que'est-ce que u as corrigé car j'utilise (en production) la version de développement.

**Comment by mathieu269** [comment]
je ne suis pas sur de comprendre la question. Github permet de voir les différences mais il suffira de remplacer l'ancienne extension par la nouvelle pour utiliser les nouvelles fonctionnalités.

**Comment by jackplux** [comment]
C'est parce que (grâce à Philippe) je découvre Github et ne suis pas encore
familiarisé avec son fonctionnement.
Ce qu'il me faut, c'est un lien vers le fichier que tu as modifié afin que
j'applique le patch sur mon site
http://orgues-barbarie-toulouse.org.

Tout va bien !
Jack Paloque-Berges
Contact: 0622622809 & 0561884364
La Page des Ouailles <http://paloque.wordpress.com/>

http://jo.reseauk.info/
http://www.lamaisondunet.org/
http://www.orgues-barbarie-toulouse.org
http://luchon-colors.com/





2016-07-17 18:22 GMT+02:00 mathieu269 <notifications@github.com>:

**Comment by mathieu269** [comment]
Github est là pour organiser le développement. Si tu as une question sur l'utilisation de l'extension cela se passe sur le forum.

**Comment by jackplux** [comment]
Je ne sais même pas ce que tu veux dire par "extension".

Pour les forums (de Pluxml), il me semble que nous avons convenu de ne les
utiliser que pour l'utilisation réservant GitHub pour les bugs et le
développement.

A moins que je n'ais riern compris. ;)

Tout va bien !
Jack Paloque-Berges
Contact: 0622622809 & 0561884364
La Page des Ouailles <http://paloque.wordpress.com/>

http://jo.reseauk.info/
http://www.lamaisondunet.org/
http://www.orgues-barbarie-toulouse.org
http://luchon-colors.com/





2016-07-17 18:28 GMT+02:00 mathieu269 <notifications@github.com>:

**Comment by ppmt** [comment]
Cool. J'ai hate de voir comment tu as resolu le probleme.
